name: Rust

on:
  release:
    types:
      - created

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Build deb package
      run: cargo deb
    - name: Upload Artifacts to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/debian/rofi-menus_${{ github.event.release.tag_name }}_amd64.deb  # Replace with the actual path to your artifact
        asset_name: rofi-menus_${{ github.event.release.tag_name }}_amd64.deb  # Replace with the desired name of the uploaded artifact
        asset_content_type: application/deb  # Replace with the appropriate content type
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
